apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeappdeployment
  labels:
    app: myapp
spec:
  replicas: 10
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: httpd
        name: myapp
        ports:
        - containerPort: 80
